// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6355.RobotsOverParma.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc6355.RobotsOverParma.Robot;
import org.usfirst.frc6355.RobotsOverParma.RobotMap;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Timer;

/**
 * 
 */
public class AutonomousCommand extends CommandGroup {
	
    public AutonomousCommand() {
    	System.out.println("Autonomous command created.");
    	
    	// Drive forward (seconds, speed)
    	this.addSequential(new DriveForwardCommand(4.0, 0.6));
    	
    	// Turn to Angle (degrees to turn, speed)
    	this.addSequential(new TurnToAngleCommand(-160.0, 0.8), 7.0);
    	
    	// Drive forward (seconds, speed)
    	this.addSequential(new DriveForwardCommand(2.0, 0.6));

    	// Pause (so we don't jerk the robot too much.
    	this.addSequential(new DriveForwardCommand(0.5, 0.0));

    	// Drive backwards(seconds, speed)
    	this.addSequential(new DriveForwardCommand(2.0, -0.6));
    }

}
